export const periods = [
  {
    id: "early-northern",
    label: "北宋前期",
    years: "960—1067",
    short: "宋初沿袭晚唐五代以来的复杂官制，官、职与差遣常相互分离。",
    focus: "理解本官多表资序、差遣负责实际事务，以及中书门下、枢密院、三司的并立。",
    before: [
      "许多唐制职事官名已阶官化，不必实际管理本衙事务。",
      "实际工作常由带有知、判、提举、提点、管勾等字样的差遣承担。",
      "财政主要由三司系统掌握。",
    ],
    after: ["这一时期本身就是元丰改制要调整的对象。", "解读官衔时要优先识别差遣，而不能只看官名大小。"],
  },
  {
    id: "xining-yuanfeng",
    label: "熙宁—元丰",
    years: "1068—1085",
    short: "新法与元丰官制改革持续重塑中央机构、职事官与寄禄官体系。",
    focus: "观察元丰改制如何让部分三省六部官重新对应实际职掌，并以新寄禄官表示禄秩。",
    before: [
      "旧本官往往主要表示品秩、俸禄和迁转次序。",
      "三司等使职机构承担大量现实行政职能。",
      "完整官衔往往必须拆成官、职、差遣理解。",
    ],
    after: [
      "部分旧本官改换为寄禄官名称，继续表示官员资序与待遇。",
      "三省六部职事官重新承担相应实际职务。",
      "同一人物跨越改革前后时，不能用同一套字段生硬解释。",
    ],
  },
  {
    id: "yuanyou",
    label: "元祐时期",
    years: "1086—1093",
    short: "制度沿用元丰新官制，但政治方向和部分具体安排出现调整。",
    focus: "区分制度名称延续与政治用人变化，不把党争直接等同于官制完全推倒重来。",
    before: ["元丰新制已经成为重要制度底盘。", "苏轼等人重新进入中央及地方要职。"],
    after: ["职位含义仍须结合元丰新制理解。", "任命的政治意义往往需要与实际差遣和朝廷位置共同判断。"],
  },
  {
    id: "late-northern",
    label: "北宋后期",
    years: "1094—1127",
    short: "绍圣以后政治方向再变，徽宗朝又有官名与制度调整。",
    focus: "追踪责授、落职、安置等处分性任命，以及徽宗朝制度名称变化。",
    before: ["元丰以后形成的职事官与寄禄官框架仍然重要。", "政治处分会组合使用降官、落职、远州安置等手段。"],
    after: ["仅看保留的官阶可能低估实际贬谪程度。", "必须把处分词、差遣地点和是否任事一起记录。"],
  },
  {
    id: "southern",
    label: "南宋",
    years: "1127—1279",
    short: "南渡后中央与地方机构在战时环境中重建并持续调整。",
    focus: "同名机构与官职不能自动继承北宋解释，应建立独立的南宋制度版本。",
    before: ["北宋制度成为重要基础，但政权规模、战区与财政环境已经改变。"],
    after: ["枢密、都督、制置等军事行政关系更需分期研究。", "同一官名应允许多个南宋阶段版本。"],
  },
];

export const institutions = [
  {
    id: "emperor",
    name: "皇帝",
    scope: "central",
    type: "最高决策",
    periods: periods.map((period) => period.id),
    summary: "诏令、任命与重大政治决策的最终权力中心。",
    functions: ["发布诏令", "任免高级官员", "裁定重大军政事务"],
    relations: ["宰执与侍从围绕皇帝形成不同决策层次", "台谏可通过奏疏等方式影响决策"],
    caveat: "不能把制度图理解成现代内阁制；皇帝与各机构的实际互动随时期和个人而变。",
  },
  {
    id: "zhongshu-menxia",
    name: "中书门下／三省",
    scope: "central",
    type: "政务中枢",
    periods: ["early-northern", "xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    summary: "处理政令形成与执行的核心系统；元丰改制前后组织形态和官名职掌有显著变化。",
    functions: ["议政", "制敕", "审议与执行政令"],
    relations: ["与枢密院分掌文武大政", "元丰后六部纳入更清晰的职事体系"],
    caveat: "“中书门下”与“三省”的具体结构需按时期拆分，不能视为稳定不变的单一机关。",
  },
  {
    id: "privy-council",
    name: "枢密院",
    scope: "central",
    type: "军政中枢",
    periods: periods.map((period) => period.id),
    summary: "与政事堂并列的重要军政机关，掌管军机、边防与部分武官事务。",
    functions: ["军机", "边防", "武官与军事文书"],
    relations: ["与宰相系统共同构成二府格局", "下接地方军事与边防系统"],
    caveat: "枢密院并非现代意义上的单一国防部，其权力范围随时期变化。",
  },
  {
    id: "three-finance-commissions",
    name: "三司",
    scope: "central",
    type: "财计机关",
    periods: ["early-northern", "xining-yuanfeng"],
    summary: "元丰改制前掌握国家财政的重要使职系统，通常包括盐铁、度支、户部。",
    functions: ["财政收支", "盐铁等专卖与财赋", "国家预算与转运关系"],
    relations: ["与路级转运系统联系紧密", "元丰改制后相当一部分职能转入户部等机构"],
    caveat: "“三司”不是三省；名称相近但制度性质完全不同。",
  },
  {
    id: "six-ministries",
    name: "六部",
    scope: "central",
    type: "中央行政",
    periods: ["xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    summary: "吏、户、礼、兵、刑、工六部。元丰改制后其职事体系更具现实行政意义。",
    functions: ["按部门分理中央行政", "承接部分原使职机构职能", "形成职事官体系"],
    relations: ["隶属三省制度框架", "与寺监及地方官司协同"],
    caveat: "元丰前也有六部官名，但很多时候不能按改制后的实职理解。",
  },
  {
    id: "censorate",
    name: "御史台与台谏",
    scope: "central",
    type: "监察言事",
    periods: periods.map((period) => period.id),
    summary: "负责监察官员、纠劾违法失职，并通过言事影响朝政。",
    functions: ["监察", "纠劾", "言事与封驳相关功能"],
    relations: ["可弹劾中央及地方官员", "与皇帝和宰执形成制度性张力"],
    caveat: "御史台、谏院及给事中等并非完全同一系统，应继续细分。",
  },
  {
    id: "route",
    name: "路",
    scope: "local",
    type: "地方监察区",
    periods: periods.map((period) => period.id),
    summary: "宋代重要地方层级，但通常不是由一个单一行政长官统辖全部事务。",
    functions: ["财赋转运", "司法监察", "军政安抚", "仓储救荒"],
    relations: ["下辖若干州府军监", "转运、提刑、常平、安抚等机构分掌事务"],
    caveat: "不要直接把“路”等同于现代省；其权力由多个监司分割。",
  },
  {
    id: "prefecture",
    name: "州、府、军、监",
    scope: "local",
    type: "地方行政",
    periods: periods.map((period) => period.id),
    summary: "地方治理的关键层级，知州等官主持行政，通判等官协理并形成牵制。",
    functions: ["民政", "司法", "财政征收", "地方治安与军政"],
    relations: ["上接路级监司", "下辖县"],
    caveat: "州、府、军、监名称与地位并不完全相同，后续要建立独立类型。",
  },
  {
    id: "county",
    name: "县",
    scope: "local",
    type: "基层行政",
    periods: periods.map((period) => period.id),
    summary: "直接面对户籍、税役、诉讼与治安事务的基层治理单位。",
    functions: ["户籍与税役", "诉讼", "治安", "地方工程"],
    relations: ["隶属于州级单位", "与乡里、胥吏和地方社会直接互动"],
    caveat: "县级官属与具体职掌因时期和县等不同而变化。",
  },
  {
    id: "entry-status",
    name: "入仕与官员类别",
    scope: "identity",
    type: "身份起点",
    periods: periods.map((period) => period.id),
    summary: "进士、荫补等入仕途径影响初授官、迁转速度与官员类别。",
    functions: ["确定入仕资格", "影响初授与铨选", "形成选人、京朝官等序列"],
    relations: ["与铨选、磨勘和荐举相连", "不同出身在部分时期对应不同初授路径"],
    caveat: "“出身”“官”“差遣”是不同字段，不应混成一个职位名称。",
  },
  {
    id: "salary-rank",
    name: "寄禄官与官阶",
    scope: "identity",
    type: "资序待遇",
    periods: ["xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    summary: "主要表示官员的品秩、禄俸、班序与迁转资序，不直接等于实际工作。",
    functions: ["确定待遇", "体现资序", "作为迁转体系的一部分"],
    relations: ["可与职名和实际差遣并列", "需与职事官品位比较理解行、守、试等称谓"],
    caveat: "不同阶段寄禄官名称和阶序会调整，应使用版本化数据。",
  },
  {
    id: "literary-title",
    name: "馆职、贴职与学士",
    scope: "identity",
    type: "资望职名",
    periods: periods.map((period) => period.id),
    summary: "往往体现文学侍从资格、资望和政治身份，未必表示实际管理某阁馆。",
    functions: ["标识清选与资望", "作为外任时所带职名", "进入侍从层的身份标志"],
    relations: ["可与寄禄官和地方差遣组合", "与翰林、馆阁系统相关但并非一概相同"],
    caveat: "“学士”类名目很多，制度层级与实际职掌不能一概而论。",
  },
];

export const titles = [
  {
    id: "zhizhou",
    name: "知州",
    fullName: "知某州军州事",
    aliases: ["知杭州军州事", "知密州", "知徐州", "知杭州", "知州"],
    category: "地方差遣",
    badge: "duty",
    periods: periods.map((period) => period.id),
    institution: "州、府、军、监",
    role: "通常是实际职务",
    summary: "主持一州的行政、司法、财政与治安等事务，是解读完整官衔时的高优先级信息。",
    plain: "真正负责一州地方治理的人。",
    relationships: ["上受路级监司监督", "与通判共同处理州政", "下辖县级官司"],
    caveat: "州的等级、辖区和是否兼带军政任务不同，具体权责需按地点与时期核对。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》及地方官制研究",
  },
  {
    id: "tongpan",
    name: "通判",
    fullName: "通判某州军州事",
    aliases: ["杭州通判", "通判杭州", "通判"],
    category: "地方差遣",
    badge: "duty",
    periods: periods.map((period) => period.id),
    institution: "州、府、军、监",
    role: "实际职务",
    summary: "协助知州处理政务，同时具有联署、监察和牵制地方长官的制度功能。",
    plain: "州一级的副职兼监督者，不只是普通助手。",
    relationships: ["与知州共同处理州政", "部分文书需联署", "受中央与路级机构节制"],
    caveat: "不同阶段和地区的实际权力并非完全一致。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》",
  },
  {
    id: "zhuanyunshi",
    name: "转运使",
    fullName: "某路转运使",
    aliases: ["转运副使", "转运判官", "转运使"],
    category: "路级差遣",
    badge: "duty",
    periods: periods.map((period) => period.id),
    institution: "路级监司",
    role: "实际职务",
    summary: "负责一路财赋转输，并在不同阶段兼具监察地方官与统筹财政的功能。",
    plain: "掌管一路财政运输，并监督地方行政的重要监司。",
    relationships: ["联系中央财计机构", "监督州县财赋", "与提点刑狱等路级监司并立"],
    caveat: "职权会随时期、地区与是否兼任其他差遣而变化。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》",
  },
  {
    id: "tixing",
    name: "提点刑狱",
    fullName: "提点某路刑狱公事",
    aliases: ["提点刑狱公事", "提点刑狱", "提刑"],
    category: "路级差遣",
    badge: "duty",
    periods: periods.map((period) => period.id),
    institution: "路级监司",
    role: "实际职务",
    summary: "巡视和复核一路刑狱，监察州县司法与官员执行情况。",
    plain: "一路范围内负责司法监察和案件复核的监司。",
    relationships: ["监督州县司法", "与转运、常平等路级机构平行", "向朝廷报告"],
    caveat: "其职掌也可能涉及治安、赈恤等附带事务，需按制度阶段核对。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》",
  },
  {
    id: "zhongshusheren",
    name: "中书舍人",
    fullName: "中书舍人",
    aliases: ["中书舍人", "舍人"],
    category: "中央职事官",
    badge: "office",
    periods: ["xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    institution: "中书省",
    role: "实际中央职务",
    summary: "元丰新制下参与起草和处理制敕等中书省事务，属于重要文翰与政令职位。",
    plain: "在中央负责重要诏令文书的高级职事官。",
    relationships: ["隶属中书省", "与给事中等形成政令起草和审议环节"],
    caveat: "改制前后的“舍人”相关名目及职掌应分开处理。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》与元丰官制研究",
  },
  {
    id: "jishizhong",
    name: "给事中",
    fullName: "给事中",
    aliases: ["给事中"],
    category: "中央职事官",
    badge: "office",
    periods: ["xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    institution: "门下省",
    role: "实际中央职务",
    summary: "参与审读政令，并具有封驳不当制敕的制度功能。",
    plain: "负责审核诏令、发现问题时可以封还驳正。",
    relationships: ["隶属门下省", "与中书省制敕流程相衔接", "具有审议与封驳功能"],
    caveat: "制度实际运作受政治环境影响，不能只按纸面权限判断。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》",
  },
  {
    id: "hanlinxueshi",
    name: "翰林学士",
    fullName: "翰林学士",
    aliases: ["翰林学士承旨", "学士承旨", "翰林学士"],
    category: "侍从职务／职名",
    badge: "honor",
    periods: periods.map((period) => period.id),
    institution: "翰林学士院",
    role: "侍从与重要文翰",
    summary: "承担重要诏令文书和皇帝顾问等职责，地位清要；具体名目与职掌需按时期细分。",
    plain: "皇帝身边负责重要文书与顾问事务的清要职位。",
    relationships: ["直接接近皇帝", "与制诰系统相关", "可成为进入更高政治核心的重要资历"],
    caveat: "不能与所有“某阁学士”视为同一性质。",
    readingPriority: "高",
    sourceHint: "《宋史·职官志》",
  },
  {
    id: "zhizhigao",
    name: "知制诰",
    fullName: "知制诰",
    aliases: ["知制诰"],
    category: "中央差遣／文翰",
    badge: "duty",
    periods: ["early-northern", "xining-yuanfeng", "yuanyou"],
    institution: "制诰系统",
    role: "实际文翰差遣",
    summary: "负责起草制诰，是理解元丰改制前中央文职运作的重要差遣之一。",
    plain: "替朝廷起草正式诏令文书。",
    relationships: ["与翰林学士分担不同层次文书", "元丰改制后相关职能纳入新职事官体系"],
    caveat: "不同阶段作为差遣、带衔或兼任时性质可能不同。",
    readingPriority: "高",
    sourceHint: "宋代文书与官制研究",
  },
  {
    id: "chaofenglang",
    name: "朝奉郎",
    fullName: "朝奉郎",
    aliases: ["朝奉郎"],
    category: "寄禄官",
    badge: "rank",
    periods: ["xining-yuanfeng", "yuanyou", "late-northern", "southern"],
    institution: "文官寄禄官阶",
    role: "资序与待遇",
    summary: "主要用来表示文官的官阶、资序和禄秩，不能据此直接判断其日常工作。",
    plain: "说明这个人的级别和待遇，不说明他具体在做什么。",
    relationships: ["可与学士等职名并列", "可与知州等实际差遣同时出现"],
    caveat: "具体品位、迁转次序和不同时期名称仍需依据官品表核定。",
    readingPriority: "中",
    sourceHint: "元丰寄禄官制度研究",
  },
  {
    id: "longtuxueshi",
    name: "龙图阁学士",
    fullName: "龙图阁学士",
    aliases: ["龙图阁直学士", "龙图阁待制", "龙图阁学士"],
    category: "馆阁职名／贴职",
    badge: "honor",
    periods: periods.map((period) => period.id),
    institution: "殿阁职名体系",
    role: "资望与侍从身份",
    summary: "通常体现文学资望、侍从身份和政治地位，外任时可与地方差遣同时出现。",
    plain: "一种体现资望的高级职名，并不等于每天管理龙图阁。",
    relationships: ["可作为知州等外任官的带职", "与其他殿阁学士、待制构成资望序列"],
    caveat: "学士、直学士、待制、直阁层级不同，不能只按关键词合并。",
    readingPriority: "中",
    sourceHint: "宋代馆阁与贴职制度研究",
  },
  {
    id: "dalipingshi",
    name: "大理评事",
    fullName: "大理评事",
    aliases: ["大理评事"],
    category: "元丰前本官",
    badge: "rank",
    periods: ["early-northern", "xining-yuanfeng"],
    institution: "大理寺官名系统",
    role: "多用于表示官员资序",
    summary: "在北宋前期完整官衔中，常不能按“实际在大理寺审案”理解，需结合所带差遣判断实际工作。",
    plain: "很多时候更像官阶名称，真正工作要看后面的差遣。",
    relationships: ["可与签书判官等差遣并列", "元丰改制后其阶官功能由新寄禄官名称承接"],
    caveat: "具体任职个案仍需核对是否实际理本寺事务。",
    readingPriority: "中",
    sourceHint: "元丰前官与差遣制度研究",
  },
  {
    id: "qianshupanguan",
    name: "签书判官厅公事",
    fullName: "签书某府判官厅公事",
    aliases: ["签书凤翔府判官厅公事", "签书判官厅公事", "签书凤翔府判官"],
    category: "地方幕职差遣",
    badge: "duty",
    periods: ["early-northern", "xining-yuanfeng"],
    institution: "府州幕职",
    role: "实际职务",
    summary: "在府州幕职系统中承办文书和行政事务，是理解苏轼早期凤翔任官的关键差遣。",
    plain: "在凤翔府实际办理地方行政文书和判官厅事务。",
    relationships: ["隶属府州长官系统", "与本官大理评事并列出现"],
    caveat: "幕职官具体分工需结合当地官署与任命文本。",
    readingPriority: "高",
    sourceHint: "苏轼年谱与宋代幕职官研究",
  },
  {
    id: "tuanlianfushi",
    name: "团练副使",
    fullName: "某州团练副使",
    aliases: ["黄州团练副使", "团练副使"],
    category: "武阶性官名／处分组合",
    badge: "rank",
    periods: ["early-northern", "xining-yuanfeng", "yuanyou", "late-northern"],
    institution: "州郡武官名号系统",
    role: "在部分文官贬谪中并非实际掌军",
    summary: "用于苏轼黄州等贬谪语境时，不能理解为实际担任当地军事副长官；需与“本州安置”等处分语合看。",
    plain: "苏轼在黄州时这是贬官名号，不代表他实际指挥黄州军队。",
    relationships: ["常与安置、不得签书公事等处分限制相连", "政治意义大于实际职掌"],
    caveat: "对其他人物和时期不能一概视为虚衔，应按任命文本核对。",
    readingPriority: "高",
    sourceHint: "苏轼年谱与宋代责降制度研究",
  },
  {
    id: "anzhi",
    name: "安置",
    fullName: "某州安置",
    aliases: ["本州安置", "黄州安置", "惠州安置", "儋州安置", "安置"],
    category: "处分状态",
    badge: "duty",
    periods: periods.map((period) => period.id),
    institution: "贬谪与居住管制",
    role: "限制性处分",
    summary: "表示被指定在某地居住并接受约束，不是普通的地方任职名称。",
    plain: "被贬后限定在某地居住，并不等于在那里担任正常职务。",
    relationships: ["常与责授、落职或低阶官名并用", "需记录能否签书公事、是否允许自由迁移等限制"],
    caveat: "不同处分等级与具体限制需要依据诏令、编敕和个案材料核实。",
    readingPriority: "高",
    sourceHint: "宋代贬谪制度研究",
  },
];

export const people = [
  {
    id: "su-shi",
    name: "苏轼",
    birthDeath: "1037—1101",
    note: "以下仅录入用于验证数据模型的代表性节点，日期、完整官衔与制度含义仍需依据年谱逐条校订。",
    appointments: [
      {
        year: 1061,
        title: "大理评事、签书凤翔府判官厅公事",
        place: "凤翔府",
        period: "early-northern",
        status: "初入仕途",
        actual: "签书凤翔府判官厅公事",
        rank: "大理评事",
        political: "地方幕职",
        interpretation: "“大理评事”主要体现本官资序；真正工作是凤翔府判官厅的地方行政事务。",
        titleIds: ["dalipingshi", "qianshupanguan"],
      },
      {
        year: 1071,
        title: "通判杭州",
        place: "杭州",
        period: "xining-yuanfeng",
        status: "外任",
        actual: "杭州通判",
        rank: "待核",
        political: "地方副职与监察",
        interpretation: "实际担任杭州通判，既协助知州，也具有牵制和监察地方长官的制度意义。",
        titleIds: ["tongpan"],
      },
      {
        year: 1074,
        title: "知密州",
        place: "密州",
        period: "xining-yuanfeng",
        status: "地方主政",
        actual: "知密州",
        rank: "待核",
        political: "一州主官",
        interpretation: "实际主持密州政务，判断其政治位置时要把地方主政与离开中央同时考虑。",
        titleIds: ["zhizhou"],
      },
      {
        year: 1077,
        title: "知徐州",
        place: "徐州",
        period: "xining-yuanfeng",
        status: "地方主政",
        actual: "知徐州",
        rank: "待核",
        political: "一州主官",
        interpretation: "继续担任地方主官；后续应叠加徐州的军事、河防和地域属性。",
        titleIds: ["zhizhou"],
      },
      {
        year: 1080,
        title: "黄州团练副使、本州安置",
        place: "黄州",
        period: "xining-yuanfeng",
        status: "贬谪",
        actual: "无正常地方主政差遣",
        rank: "黄州团练副使",
        political: "远离政治中心并受限制",
        interpretation: "“团练副使”在此不表示实际掌军；“本州安置”才揭示这是一项限制性贬谪。",
        titleIds: ["tuanlianfushi", "anzhi"],
      },
      {
        year: 1089,
        title: "龙图阁学士、知杭州",
        place: "杭州",
        period: "yuanyou",
        status: "带职外任",
        actual: "知杭州",
        rank: "寄禄官待补",
        political: "高资望地方主官",
        interpretation: "实际工作是主持杭州政务；龙图阁学士体现较高资望和侍从身份。",
        titleIds: ["longtuxueshi", "zhizhou"],
      },
      {
        year: 1094,
        title: "贬谪岭南（示例节点，完整官衔待录）",
        place: "惠州等",
        period: "late-northern",
        status: "再次贬谪",
        actual: "受安置限制",
        rank: "待据年谱逐条录入",
        political: "远离中央",
        interpretation: "此节点保留为数据缺口示范：系统必须允许“不完整记录”和后续史料校订。",
        titleIds: ["anzhi"],
      },
    ],
  },
  {
    id: "wang-anshi",
    name: "王安石",
    birthDeath: "1021—1086",
    note: "暂录少量占位节点，用于证明人物并非围绕苏轼单独建模。",
    appointments: [
      {
        year: 1069,
        title: "参知政事（示例）",
        place: "开封",
        period: "xining-yuanfeng",
        status: "执政",
        actual: "参与最高政务",
        rank: "待补",
        political: "中央核心",
        interpretation: "后续需补入完整除授文本、时间和与新法机构的关系。",
        titleIds: [],
      },
      {
        year: 1076,
        title: "罢相后外任（示例）",
        place: "江宁",
        period: "xining-yuanfeng",
        status: "退出中枢",
        actual: "地方任职待补",
        rank: "待补",
        political: "离开中央核心",
        interpretation: "用于演示政治位置与官阶并不总是同步变化。",
        titleIds: [],
      },
    ],
  },
  {
    id: "sima-guang",
    name: "司马光",
    birthDeath: "1019—1086",
    note: "暂录少量占位节点，后续可与元祐更化、馆职和宰执体系结合。",
    appointments: [
      {
        year: 1071,
        title: "退居洛阳修书（官衔待补）",
        place: "洛阳",
        period: "xining-yuanfeng",
        status: "离开政治中枢",
        actual: "编修与学术活动",
        rank: "待补",
        political: "政治中心度降低",
        interpretation: "系统需要区分保留的官衔、实际差遣和现实政治影响。",
        titleIds: [],
      },
      {
        year: 1085,
        title: "入朝任职（示例节点）",
        place: "开封",
        period: "yuanyou",
        status: "重返中枢",
        actual: "中央政务",
        rank: "待补",
        political: "中央核心",
        interpretation: "后续逐条补录元祐初年除授，以比较政治变动与制度连续性。",
        titleIds: [],
      },
    ],
  },
];

export const categories = [...new Set(titles.map((title) => title.category))];
